datasets:
  wine:
    column_mapping:
        
      numerical_features:
        - 'volatile_acidity'
        - 'free_sulfur_dioxide'
        - 'total_sulfur_dioxide'
        - 'alcohol'
      prediction:
        - 'quality'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: ./datasets/winequality.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
